/* -------- This file has been automatically generated by configure ---------
   Note: Any changes in it will be lost when you run configure again. */

/* use GNU internationalization */
//#define USE_I18N 1

/* use setlocale() function */
#define USE_SETLOCALE 1

/* Runtime CPU detection */
#define RUNTIME_CPUDETECT 1

/* Dynamic a/v plugins */
#undef DYNAMIC_PLUGINS

/* "restrict" keyword */
#define restrict __restrict

#define PREFIX "/usr/local"

/* define this to use simple idct with patched libavcodec */
#define SIMPLE_IDCT 1

#define USE_OSD 1
#define USE_SUB 1

/* enable/disable SIGHANDLER */
#define ENABLE_SIGHANDLER 1

/* Toggles debugging informations */
#undef MP_DEBUG

/* Indicates that Ogle's libdvdread is available for DVD playback */
#define USE_DVDREAD 1

/* Indicates that dvdread is from libmpdvdkit */
#define USE_MPDVDKIT 2

/* Additional options for libmpdvdkit*/
#undef DVD_STRUCT_IN_DVD_H
#undef DVD_STRUCT_IN_LINUX_CDROM_H
#undef DVD_STRUCT_IN_SYS_CDIO_H
#undef DVD_STRUCT_IN_SYS_DVDIO_H
#undef DVD_STRUCT_IN_BSDI_DVDIOCTL_DVD_H
#undef HAVE_BSD_DVD_STRUCT
#undef HAVE_LINUX_DVD_STRUCT
#undef HAVE_OPENBSD_DVD_STRUCT
#undef DARWIN_DVD_IOCTL
#undef SOLARIS_USCSI
#undef HPUX_SCTL_IO
#define HAVE_STDDEF_H 1

/* Common data directory (for fonts, etc) */
#define MPLAYER_DATADIR "/usr/local/share/mplayer"
#define MPLAYER_CONFDIR "/usr/local/etc/mplayer"
#define MPLAYER_LIBDIR "/usr/local/lib"

/* Define this to compile stream-caching support, it can be enabled via
   -cache <kilobytes> */
#define USE_STREAM_CACHE 1

/* Define to include support for XviD/Divx4Linux/OpenDivx */
#undef USE_DIVX

/* Define to use the new XviD/DivX4Linux library instead of open source OpenDivX */
/* You have to change DECORE_LIBS in config.mak, too! */
#undef NEW_DECORE

/* Define if you are using DivX5Linux Decore library */
#undef DECORE_DIVX5

/* Define if you are using XviD library */
#undef HAVE_XVID
#undef DECORE_XVID
#undef ENCORE_XVID

/* Define to include support for libdv-0.9.5 */
#undef HAVE_LIBDV095

/* If build mencoder */
#define HAVE_MENCODER

/* Indicates if XviD/Divx4linux encore is available
   Note: for mencoder */
#undef HAVE_DIVX4ENCORE

/* Indicates if libmp3lame is available
   Note: for mencoder */
#undef HAVE_MP3LAME

/* Define libmp1e for realtime mpeg encoding (for DXR3 and DVB cards) */
#undef USE_MP1E

/* Define this to enable avg. byte/sec-based AVI sync method by default:
   (use -bps or -nobps commandline option for run-time method selection)
   -bps gives better sync for vbr mp3 audio, it is now default */
#define AVI_SYNC_BPS 1

/* Undefine this if you do not want to select mono audio (left or right)
   with a stereo MPEG layer 2/3 audio stream. The command line option
   -stereo has three possible values (0 for stereo, 1 for left-only, 2 for
   right-only), with 0 being the default.
   */
#define USE_FAKE_MONO 1

/* Undefine this if your sound card driver has no working select().
   If you have kernel Oops, player hangups, or just no audio, you should
   try to recompile MPlayer with this option disabled! */
#define HAVE_AUDIO_SELECT 1

/* define this to use iconv(3) function to codepage conversions */
#define USE_ICONV 1

/* define this to use RTC (/dev/rtc) for video timers (LINUX only) */
#undef HAVE_RTC

/* set up max. outburst. use 65536 for ALSA 0.5, for others 16384 is enough */
#define MAX_OUTBURST 65536

/* set up audio OUTBURST. Do not change this! */
#define OUTBURST 512

/* Define this if your system has the header file for the OSS sound interface */
#define HAVE_SYS_SOUNDCARD_H 1

/* Define this if your system has the header file for the OSS sound interface
 * in /usr/include */
#undef HAVE_SOUNDCARD_H

/* Define this if your system has the sysinfo header */
#undef HAVE_SYS_SYSINFO_H

/* Define this if your system uses ftello() for off_t seeking */

#define HAVE_FTELLO 1
#ifndef HAVE_FTELLO
# define ftello(a) ftell(a)
#endif

/* Define this if your system has the "malloc.h" header file */
#define HAVE_MALLOC_H 1

/* memalign is mapped to malloc if unsupported */
#define HAVE_MEMALIGN 1
#ifndef HAVE_MEMALIGN
# define memalign(a,b) malloc(b)
#endif

/* Define this if your system has the "alloca.h" header file */
#define HAVE_ALLOCA_H 1

/* Define this if your system has the "sys/mman.h" header file */
#define HAVE_SYS_MMAN_H 1

/* Define this if you have the elf dynamic linker -ldl library */
#define HAVE_LIBDL 1

/* Define this if you have the kstat kernel statistics library */
#undef HAVE_LIBKSTAT

/* Define this if you have zlib */
#define HAVE_ZLIB 1

/* Define this if you have shm support */
#define HAVE_SHM 1

/* Define this if your system has scandir & alphasort */
#define HAVE_SCANDIR 1

/* Define this if your system has strsep */
#define HAVE_STRSEP 1

/* Define this if your system has vsscanf */
#define HAVE_VSSCANF 1

/* Define this if your system has no posix select */
#undef HAVE_NO_POSIX_SELECT

/* Define this if your system has gettimeofday */
#define HAVE_GETTIMEOFDAY 1

/* Define this if your system has glob */
#define HAVE_GLOB 1

/* LIRC (remote control, see www.lirc.org) support: */
#undef HAVE_LIRC

/*
 * LIRCCD (LIRC client daemon)
 * See http://www.dolda2000.cjb.net/~fredrik/lirccd/
 */
#undef HAVE_LIRCC

/* DeCSS support using libcss */
#undef HAVE_LIBCSS

/* DVD navigation support using libdvdnav */



/* Define this to enable MPEG 1/2 image postprocessing (requires a FAST CPU!) */
#define MPEG12_POSTPROC 1

/* Define this to enable image postprocessing in libavcodec (requires a FAST CPU!) */
#define FF_POSTPROCESS 1

/* Define to include support for OpenDivx postprocessing */
#undef HAVE_ODIVX_POSTPROCESS

/* Win32 DLL support */
#undef USE_WIN32DLL
#define WIN32_PATH ""

/* DirectShow support */
#undef USE_DIRECTSHOW

/* Mac OS X specific features */
#undef MACOSX

/* Build our Win32-loader */


/* ffmpeg's libavcodec support (requires libavcodec source) */
#define USE_LIBAVCODEC 1
#undef USE_LIBAVCODEC_SO

/* risky codecs */
#define CONFIG_RISKY 1

/* Use libavcodec's decoders */
#define CONFIG_DECODERS 1
/* Use libavcodec's encoders */
#define CONFIG_ENCODERS 1

/* Use codec libs included in mplayer CVS / source dist: */
#define USE_MP3LIB
#define USE_LIBA52
#define USE_LIBMPEG2

/* Use the SVQ1 decoder in libmpcodecs - we don't want/need it with libavcodec */
#ifndef USE_LIBAVCODEC
#define USE_SVQ1
#endif

/* Use libfame encoder filter */
#undef USE_LIBFAME

/* XAnim DLL support */
#undef USE_XANIM
/* Default search path */
#undef XACODEC_PATH

/* RealPlayer DLL support */
#undef USE_REALCODECS
/* Default search path */
#undef REALCODEC_PATH

/* LIVE.COM Streaming Media library support */
#undef STREAMING_LIVE_DOT_COM

/* Use 3dnow/mmxext/sse/mmx optimized fast memcpy() [maybe buggy... signal 4]*/
#define USE_FASTMEMCPY 1

/* Use unrarlib for Vobsubs */
#define USE_UNRARLIB 1

/* gui support, please do not edit this option */
//#define HAVE_NEW_GUI 1

/* Audio output drivers */
#define USE_OSS_AUDIO 1
#define PATH_DEV_DSP "/dev/dsp"
#define PATH_DEV_MIXER "/dev/mixer"
#undef HAVE_ALSA5
#undef HAVE_ALSA9

#undef USE_ESD
#undef HAVE_ESD_LATENCY
#undef HAVE_SYS_ASOUNDLIB_H
#undef HAVE_ALSA_ASOUNDLIB_H
#undef USE_SUN_AUDIO
#undef USE_SGI_AUDIO
#define HAVE_WIN32WAVEOUT 1
#undef HAVE_NAS

/* Enable fast OSD/SUB renderer (looks ugly, but uses less CPU power) */
#undef FAST_OSD
#undef FAST_OSD_TABLE

/* Enable TV Interface support */
#define USE_TV 1

/* Enable EDL support */
#define USE_EDL

/* Enable Video 4 Linux TV interface support */
#undef HAVE_TV_V4L2

/* Enable Video 4 Linux 2 TV interface support */


/* Enable *BSD BrookTree TV interface support */
#undef HAVE_TV_BSDBT848

/* Define if your processor stores words with the most significant
   byte first (like Motorola and SPARC, unlike Intel and VAX).  */
#undef WORDS_BIGENDIAN

#define ARCH_X86 1

/* libmpeg2 wants ARCH_PPC and the rest of mplayer use ARCH_POWERPC,
 * define ARCH_PPC if ARCH_POWERPC is set to cope with that.
 */
#ifdef ARCH_POWERPC
#define ARCH_PPC 1
#endif

/* the same issue as with ARCH_POWERPC but with ffmpeg/libavcodec */
#ifdef ARCH_ARMV4L
#define ARCH_ARM 1
#endif

/* only gcc3 can compile mvi instructions */


/* Define this for Cygwin build for win32 */
#define WIN32

/* Define this to any prefered value from 386 up to infinity with step 100 */
#define __CPU__ 686

#define MP_WORDSIZE 32

#undef TARGET_LINUX

#undef HAVE_VCD

#ifdef sun
#define	DEFAULT_CDROM_DEVICE	"/vol/dev/aliases/cdrom0"
#define DEFAULT_DVD_DEVICE	DEFAULT_CDROM_DEVICE
#elif defined(HPUX)
#define DEFAULT_CDROM_DEVICE    "/dev/cdrom"
#define DEFAULT_DVD_DEVICE     "/dev/dvd"
#elif defined(WIN32)
#define DEFAULT_CDROM_DEVICE    "D:"
#define DEFAULT_DVD_DEVICE	"D:"
#elif defined(SYS_DARWIN)
#define DEFAULT_CDROM_DEVICE    "/dev/rdiskN"
#define DEFAULT_DVD_DEVICE	DEFAULT_CDROM_DEVICE
#else
#define DEFAULT_CDROM_DEVICE    "/dev/cdrom"
#define DEFAULT_DVD_DEVICE	"/dev/dvd"
#endif


/*----------------------------------------------------------------------------
**
** NOTE: Instead of modifying these definitions here, use the
**       --enable/--disable options of the ./configure script!
**       See ./configure --help for details.
**
*---------------------------------------------------------------------------*/

/* C99 lrintf function available */
#define HAVE_LRINTF 1

/* nanosleep support */
#define HAVE_NANOSLEEP 1

/* SMB support */
#undef LIBSMBCLIENT

/* termcap flag for getch2.c */
#define USE_TERMCAP 1

/* termios flag for getch2.c */
#define HAVE_TERMIOS 1
#undef HAVE_TERMIOS_H
#define HAVE_SYS_TERMIOS_H 1

/* enable PNG support */
#define HAVE_PNG 1

/* enable JPEG support */
#define HAVE_JPEG 1

/* enable GIF support */
#define HAVE_GIF 1
#undef HAVE_GIF_4
#undef HAVE_GIF_TVT_HACK

/* enable FreeType support */
#define HAVE_FREETYPE

/* enable FriBiDi usage */
#undef USE_FRIBIDI

/* liblzo support */
#undef USE_LIBLZO

/* libmad support */
#undef USE_LIBMAD

/* enable OggVorbis support */
#undef HAVE_OGGVORBIS

/* enable Tremor as vorbis decoder */
#undef TREMOR

/* enable OggTheora support */
#undef HAVE_OGGTHEORA

/* enable Matroska support */
#undef HAVE_MATROSKA

/* enable FAAD (AAC) support */
#define HAVE_FAAD 1
#define FAADVERSION 20

/* enable network */
#define MPLAYER_NETWORK 1

/* enable ftp support */
#define HAVE_FTP 1

/* enable winsock2 instead of Unix functions*/
#undef HAVE_WINSOCK2

/* define this to use inet_aton() instead of inet_pton() */
#define USE_ATON 1

/* enables / disables cdparanoia support */
#undef HAVE_CDDA

/* enables / disables VIDIX usage */
#undef CONFIG_VIDIX

/* enables / disables new input joystick support */
#undef HAVE_JOYSTICK

/* enables / disables QTX codecs */
#undef USE_QTX_CODECS

/* enables / disables osd menu */
#undef HAVE_MENU

/* enables / disables subtitles sorting */
#define USE_SORTSUB 1

/* XMMS input plugin support */
#undef HAVE_XMMS
#define XMMS_INPUT_PLUGIN_DIR ""

/* enables inet6 support */
#undef HAVE_AF_INET6

/* do we have gethostbyname2? */
#undef HAVE_GETHOSTBYNAME2

/* Extension defines */
#define HAVE_3DNOW 1	// only define if you have 3DNOW (AMD k6-2, AMD Athlon, iDT WinChip, etc.)
#define HAVE_3DNOWEX 1	// only define if you have 3DNOWEX (AMD Athlon, etc.)
#define HAVE_MMX 1	// only define if you have MMX (newer x86 chips, not P54C/PPro)
#define HAVE_MMX2 1	// only define if you have MMX2 (Athlon/PIII/4/CelII)
#define HAVE_SSE 1	// only define if you have SSE (Intel Pentium III/4 or Celeron II)
#define HAVE_SSE2 1	// only define if you have SSE2 (Intel Pentium 4)
#undef HAVE_ALTIVEC	// only define if you have Altivec (G4)

#ifdef HAVE_MMX
#define USE_MMX_IDCT 1
#endif

#undef HAVE_ALTIVEC_H	// enables usage of altivec.h


#undef HAVE_MLIB  // Sun mediaLib, available only on solaris

/* libmpeg2 uses a different feature test macro for mediaLib */
#ifdef HAVE_MLIB
#define LIBMPEG2_MLIB 1
#endif

/* libvo options */
#define SCREEN_SIZE_X 1
#define SCREEN_SIZE_Y 1
#define HAVE_X11 1
#define HAVE_XV 1
#undef HAVE_XVMC
#define HAVE_XF86VM 1
#undef HAVE_XINERAMA
#undef HAVE_GL
#undef HAVE_DGA
#undef HAVE_DGA2
#define HAVE_SDL 1
/* defined for SDLlib with keyrepeat bugs (before 1.2.1) */
#undef BUGGY_SDL
#define HAVE_DIRECTX 1
#undef HAVE_GGI
#undef HAVE_3DFX
#undef HAVE_TDFXFB
#undef HAVE_TDFX_VID
#undef HAVE_DIRECTFB

#undef HAVE_ZR
#undef HAVE_BL
#undef HAVE_MGA
#undef HAVE_XMGA

#undef HAVE_FBDEV
#undef HAVE_DXR2
#undef HAVE_DXR3
#undef HAVE_DVB
#undef HAS_DVBIN_SUPPORT 
#undef HAVE_SVGALIB
#undef HAVE_VESA
#define HAVE_XDPMS 1
#undef HAVE_AA
#define HAVE_TGA 1

/* used by GUI: */
#define HAVE_XSHAPE 1

#if defined(HAVE_GL) || defined(HAVE_X11) || defined(HAVE_XV)
#define X11_FULLSCREEN 1
#endif

