/*
 * Copyright(c) 2000 UltraMaster Group
 *
 * License to use UltraMaster Juno-6 is provided free of charge subject to the 
 * following restrictions:
 *
 * 1.) This license is for your personal use only.
 *
 * 2.) No portion of this software may be redistributed by you to any other 
 *     person in any form. 
 *
 * 3.) You may not sell UltraMaster Juno-6 to any person.
 *
 * 4.) UltraMaster Juno-6 is provided without any express or implied warranty. 
 *     In no event shall UltraMaster Group be held liable for any damages 
 *     arising from the use of UltraMaster Juno-6.
 */
/* XPM */
static char *sw_2way_up_pix[] = {
/* columns rows colors chars-per-pixel */
"9 24 16 1",
"  c Gray0",
". c Gray100",
"X c #e6e6e6",
"o c Gray80",
"O c Gray70",
"+ c Gray60",
"@ c #808080",
"# c Gray40",
"$ c #4c4c4c",
"% c Gray20",
"& c #191919",
"* c Gray0",
"= c Gray0",
"- c Gray0",
"; c Gray0",
": c Gray0",
/* pixels */
"%%%%%%%%%",
"%%%%%%%%%",
"%%%%%%%%%",
"%%%%%%%%%",
"%%%%%%%%%",
"%%%%%%%%%",
"%%%%%%%%%",
"%%%%%%%%%",
"%%&&&&&%%",
"%&     &%",
"&  ...  &",
"& ..... &",
"& ..... &",
"& ..... &",
"&  ...  &",
"&       &",
"&       &",
"&       &",
"&       &",
"&       &",
"&       &",
"&       &",
"%&     &%",
"%%&&&&&%%"
};
/* XPM */
static char *sw_2way_down_pix[] = {
/* columns rows colors chars-per-pixel */
"9 24 16 1",
"  c Gray0",
". c Gray100",
"X c #e6e6e6",
"o c Gray80",
"O c Gray70",
"+ c Gray60",
"@ c #808080",
"# c Gray40",
"$ c #4c4c4c",
"% c Gray20",
"& c #191919",
"* c Gray0",
"= c Gray0",
"- c Gray0",
"; c Gray0",
": c Gray0",
/* pixels */
"%%%%%%%%%",
"%%%%%%%%%",
"%%%%%%%%%",
"%%%%%%%%%",
"%%%%%%%%%",
"%%%%%%%%%",
"%%%%%%%%%",
"%%%%%%%%%",
"%%&&&&&%%",
"%&     &%",
"&  &&&  &",
"& &%%%& &",
"& %$$$% &",
"& $###$ &",
"& #@@@# &",
"& @+++@ &",
"& +OOO+ &",
"& OoooO &",
"& oXXXo &",
"& X...X &",
"& ..... &",
"& ..... &",
"%&.....&%",
"%%&...&%%"
};
/* XPM */
static char *sw_3way_down_pix[] = {
/* columns rows colors chars-per-pixel */
"9 24 16 1",
"  c Gray0",
". c Gray100",
"X c #e6e6e6",
"o c Gray80",
"O c Gray70",
"+ c Gray60",
"@ c #808080",
"# c Gray40",
"$ c #4c4c4c",
"% c Gray20",
"& c #191919",
"* c Gray0",
"= c Gray0",
"- c Gray0",
"; c Gray0",
": c Gray0",
/* pixels */
"%%&&&&&%%",
"%&     &%",
"&       &",
"&       &",
"&       &",
"&       &",
"&       &",
"&       &",
"&       &",
"&       &",
"&  &&&  &",
"& &%%%& &",
"& %$$$% &",
"& $###$ &",
"& #@@@# &",
"& @+++@ &",
"& +OOO+ &",
"& OoooO &",
"& oXXXo &",
"& X...X &",
"& ..... &",
"& ..... &",
"%&.....&%",
"%%&...&%%"
};
/* XPM */
static char *sw_3way_mid_pix[] = {
/* columns rows colors chars-per-pixel */
"9 24 16 1",
"  c Gray0",
". c Gray100",
"X c #e6e6e6",
"o c Gray80",
"O c Gray70",
"+ c Gray60",
"@ c #808080",
"# c Gray40",
"$ c #4c4c4c",
"% c Gray20",
"& c #191919",
"* c Gray0",
"= c Gray0",
"- c Gray0",
"; c Gray0",
": c Gray0",
/* pixels */
"%%&&&&&%%",
"%&     &%",
"&       &",
"&       &",
"&       &",
"&       &",
"&       &",
"&       &",
"&       &",
"&  ...  &",
"& ..... &",
"& ..... &",
"& ..... &",
"&  ...  &",
"&       &",
"&       &",
"&       &",
"&       &",
"&       &",
"&       &",
"&       &",
"&       &",
"%&     &%",
"%%&&&&&%%"
};
/* XPM */
static char *sw_3way_up_pix[] = {
/* columns rows colors chars-per-pixel */
"9 24 16 1",
"  c Gray0",
". c Gray100",
"X c #e6e6e6",
"o c Gray80",
"O c Gray70",
"+ c Gray60",
"@ c #808080",
"# c Gray40",
"$ c #4c4c4c",
"% c Gray20",
"& c #191919",
"* c Gray0",
"= c Gray0",
"- c Gray0",
"; c Gray0",
": c Gray0",
/* pixels */
"%%&...&%%",
"%&.....&%",
"& ..... &",
"& ..... &",
"& X...X &",
"& oXXXo &",
"& OoooO &",
"& +OOO+ &",
"& @+++@ &",
"& #@@@# &",
"& $###$ &",
"& %$$$% &",
"& &%%%& &",
"&  &&&  &",
"&       &",
"&       &",
"&       &",
"&       &",
"&       &",
"&       &",
"&       &",
"&       &",
"%&     &%",
"%%&&&&&%%"
};
